linters:
  enable:
    - bodyclose
    - contextcheck
    - gocognit
    - decorder
    - dupl
    - durationcheck
    - errname
    - errorlint
    - funlen
    - goimports
    - goconst
    - gocritic
    - gofumpt
    - ireturn
    - prealloc
    - wsl
run:
  tests: false
