# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - go build -o dist/ -v ./...
    silent: true

  fmt:
    cmds:
      - go vet ./...
      - go fmt ./...

  test:
    cmds:
      - go test -cover ./...
